// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfcK4I2I5k89FXO0qkZtOOdsTkAkF4XhU',
    appId: '1:909954924561:web:9af0cd7d40df1b539f31b0',
    messagingSenderId: '909954924561',
    projectId: 'food-go-app',
    authDomain: 'food-go-app.firebaseapp.com',
    storageBucket: 'food-go-app.firebasestorage.app',
    measurementId: 'G-HHQNCFWNVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP0T2G-b8auKZnKiIsNhJiJvYvKYuFis4',
    appId: '1:909954924561:android:599b7cffe2504e469f31b0',
    messagingSenderId: '909954924561',
    projectId: 'food-go-app',
    storageBucket: 'food-go-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTDFiA2x0xSfbCbCc6AOVChXVkbLtEoJU',
    appId: '1:909954924561:ios:df315cd0433d3a549f31b0',
    messagingSenderId: '909954924561',
    projectId: 'food-go-app',
    storageBucket: 'food-go-app.firebasestorage.app',
    iosBundleId: 'com.example.foodGoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTDFiA2x0xSfbCbCc6AOVChXVkbLtEoJU',
    appId: '1:909954924561:ios:df315cd0433d3a549f31b0',
    messagingSenderId: '909954924561',
    projectId: 'food-go-app',
    storageBucket: 'food-go-app.firebasestorage.app',
    iosBundleId: 'com.example.foodGoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfcK4I2I5k89FXO0qkZtOOdsTkAkF4XhU',
    appId: '1:909954924561:web:8c5df37109e4ec699f31b0',
    messagingSenderId: '909954924561',
    projectId: 'food-go-app',
    authDomain: 'food-go-app.firebaseapp.com',
    storageBucket: 'food-go-app.firebasestorage.app',
    measurementId: 'G-YFT6XYVBRX',
  );
}
